apt_packages:
  - 1password
  - 1password-cli
  - 7zip
  - adduser
  - alsa-utils
  - amd64-microcode
  - ansible
  - apparmor-utils
  - apt
  - apt-file
  - apt-listchanges
  - apt-utils
  - ardour
  - base-files
  - base-passwd
  - bash
  - bash-completion
  - bc
  - bind9-dnsutils
  - bind9-host
  - binutils
  - binutils-dev
  - blender
  - bridge-utils
  - bsdutils
  - build-essential
  - busybox
  - bzip2
  - ca-certificates
  - cava
  - clipman
  - cmake
  - console-setup
  - coreutils
  - cpio
  - cron
  - cron-daemon-common
  - cryptsetup
  - cryptsetup-initramfs
  - curl
  - dash
  - dbus
  - dbus-x11
  - dconf-cli
  - dconf-service
  - debconf
  - debconf-i18n
  - debhelper
  - debian-archive-keyring
  - debian-faq
  - debianutils
  - diffutils
  - discover
  - dkms
  - dmidecode
  - dmsetup
  - doc-debian
  - dosfstools
  - dpkg
  - dpkg-dev
  - e2fsprogs
  - edid-decode
  - exfatprogs
  - extrepo
  - fd-find
  - fdisk
  - ffmpeg
  - file
  - findutils
  - firmware-amd-graphics
  - firmware-iwlwifi
  - firmware-misc-nonfree
  - flatpak
  - fonts-dejavu-core
  - fonts-font-awesome
  - fonts-jetbrains-mono
  - fonts-noto-color-emoji
  - fonts-powerline
  - fonts-roboto
  - fzf
  - g++
  - gamemode
  - gamescope
  - gcc
  - gcc-12-base
  - gettext-base
  - gimp
  - git
  - gnome-themes-extra
  - gocryptfs
  - gpg
  - gpgv
  - grep
  - grim
  - grimshot
  - groff-base
  - grub-common
  - grub-efi-amd64
  - gsettings-desktop-schemas
  - gzip
  - helvum
  - hostname
  - htop
  - hydrogen
  - hyprland
  - ifupdown
  - imagemagick
  - inetutils-telnet
  - init
  - initramfs-tools
  - init-system-helpers
  - inkscape
  - installation-report
  - iproute2
  - iputils-ping
  - isc-dhcp-client
  - isc-dhcp-common
  - jq
  - kdenlive
  - keyboard-configuration
  - kmod
  - krb5-locales
  - laptop-detect
  - less
  - libacl1
  - libaml-dev
  - libapparmor1
  - libapt-pkg6.0
  - libargon2-1
  - libasound2-dev
  - libattr1
  - libaudit1
  - libaudit-common
  - libblkid1
  - libbpf1
  - libbsd0
  - libbz2-1.0
  - libbz2-dev
  - libc6
  - libc6:i386
  - libcairo2-dev
  - libcap2
  - libcap2-bin
  - libcap-ng0
  - libc-bin
  - libcom-err2
  - libcrypt1
  - libcryptsetup12
  - libdebconfclient0
  - libdevmapper1.02.1
  - libdrm-dev
  - libedit2
  - libegl1-mesa-dev
  - libegl-dev
  - libfdisk1
  - libffi8
  - libffi-dev
  - libfontconfig1-dev
  - libfontconfig-dev
  - libfreetype-dev
  - libgamemode0
  - libgamemodeauto0
  - libgcc-s1
  - libgcrypt20
  - libgdk-pixbuf-2.0-0
  - libgdk-pixbuf2.0-bin
  - libgdk-pixbuf2.0-common
  - libgl1:i386
  - libgl1-mesa-dev
  - libgl1-mesa-dri:i386
  - libgl-dev
  - libgles2-mesa-dev
  - libgles-dev
  - libglib2.0-bin
  - libglvnd-dev
  - libgmp10
  - libgnutls28-dev
  - libgpg-error0
  - libgssapi-krb5-2
  - libgtk2.0-0t64
  - libidn2-0
  - libip4tc2
  - libjansson4
  - libjansson-dev
  - libjpeg62-turbo
  - libjpeg-dev
  - libjson-c5
  - libk5crypto3
  - libkeyutils1
  - libkmod2
  - libkrb5-3
  - libkrb5support0
  - liblinux-usermod-perl
  - liblocale-gettext-perl
  - liblockfile-bin
  - liblz4-1
  - liblzma5
  - liblzma-dev
  - liblzo2-dev
  - libmd0
  - libmnl0
  - libmount1
  - libncurses-dev
  - libncursesw6
  - libneatvnc-dev
  - libnewt0.52
  - libnftables1
  - libnftnl11
  - libnss-systemd
  - libp11-kit0
  - libpam0g
  - libpam0g-dev
  - libpam-modules
  - libpam-modules-bin
  - libpam-runtime
  - libpam-systemd
  - libpcre2-8-0
  - libpipewire-0.3-dev
  - libpixman-1-dev
  - libpng16-16t64
  - libpopt0
  - libproc2-0
  - libpulse-dev
  - libqt5waylandclient5
  - libqt5waylandclient5-dev
  - libqt5waylandcompositor5
  - libqt5waylandcompositor5-dev
  - libreadline-dev
  - librewolf
  - librust-pipewire-dev
  - libsamplerate0-dev
  - libsasl2-dev
  - libseccomp2
  - libselinux1
  - libsemanage2
  - libsemanage-common
  - libsepol2
  - libslang2
  - libsmartcols1
  - libspice-protocol-dev
  - libsqlite3-dev
  - libss2
  - libssl-dev
  - libstdc++6
  - libsystemd0
  - libsystemd-shared
  - libtasn1-6
  - libtext-charwidth-perl
  - libtext-iconv-perl
  - libtext-wrapi18n-perl
  - libtinfo6
  - libtirpc-common
  - libturbojpeg0-dev
  - libudev1
  - libudev-dev
  - libunistring2
  - libuuid1
  - libvirt0
  - libvirt-clients
  - libvirt-daemon-system
  - libvpx9
  - libvpx-dev
  - libvulkan1
  - libvulkan1:i386
  - libwayland-dev
  - libx11-dev
  - libx11-xcb-dev
  - libxcb1-dev
  - libxcb-cursor0
  - libxcb-keysyms1
  - libxcb-shm0
  - libxcb-shm0-dev
  - libxcb-xfixes0-dev
  - libxcb-xkb1
  - libxcursor-dev
  - libxi-dev
  - libxinerama-dev
  - libxkbcommon0
  - libxkbcommon-dev
  - libxkbcommon-x11-0
  - libxml2-dev
  - libxmlsec1-dev
  - libxpresent-dev
  - libxrandr-dev
  - libxss-dev
  - libxtables12
  - libxxhash0
  - libzstd1
  - lilv-utils
  - linux-cpupower
  - linux-headers-6.12.27-amd64
  - linux-headers-6.12.27-common
  - linux-headers-6.12.38+deb13-amd64
  - linux-headers-6.16.3+deb14-amd64
  - linux-headers-amd64
  - linux-image-6.12.27-amd64
  - linux-image-amd64
  - llvm
  - locales
  - locate
  - login
  - logrotate
  - logsave
  - looking-glass-client
  - lsof
  - lv2-dev
  - lvm2
  - make
  - man-db
  - mangohud
  - manpages
  - mawk
  - media-types
  - mesa-vulkan-drivers
  - mesa-vulkan-drivers:i386
  - meson
  - mime-support
  - mount
  - mpv
  - nano
  - ncurses-base
  - ncurses-bin
  - ncurses-term
  - netbase
  - netcat-traditional
  - nettle-dev
  - nextcloud-desktop
  - nftables
  - ntfs-3g
  - nvidia-cuda-toolkit
  - nvidia-driver
  - obs-plugins
  - obs-studio
  - openssh-client
  - os-prober
  - ovmf
  - pamix
  - pamixer
  - papirus-icon-theme
  - passwd
  - patchelf
  - pavucontrol
  - pciutils
  - perl
  - perl-base
  - pipewire
  - pipewire-audio-client-libraries
  - pipewire-jack
  - pipewire-pulse
  - pipx
  - pkgconf
  - pkg-config
  - poppler-utils
  - powerline
  - procps
  - psmisc
  - pulseaudio-utils
  - pulsemixer
  - python3
  - python3-pip
  - python3-reportbug
  - python3-venv
  - python3-virt-firmware
  - qemu-guest-agent
  - qemu-system-x86
  - qemu-utils
  - qtwayland5
  - qtwayland5-dev-tools
  - readline-common
  - reportbug
  - restic
  - ripgrep
  - rsync
  - scdoc
  - sed
  - sensible-utils
  - shim-signed
  - slurp
  - sshfs
  - steam-installer
  - sudo
  - sway
  - swayidle
  - swayimg
  - swaylock
  - systemd
  - systemd-coredump
  - systemd-sysv
  - systemd-timesyncd
  - sysvinit-utils
  - tar
  - task-english
  - tasksel
  - tasksel-data
  - tcpdump
  - tk-dev
  - tmux
  - traceroute
  - tree
  - tzdata
  - ucf
  - udev
  - ulauncher
  - unison
  - unzip
  - usbutils
  - usr-is-merged
  - util-linux
  - util-linux-extra
  - v4l2loopback-dkms
  - v4l-utils
  - vim
  - vim-common
  - vim-tiny
  - virt-manager
  - virtualbox-guest-utils
  - vulkan-tools
  - vulkan-utility-libraries-dev
  - wamerican
  - waybar
  - wayland-protocols
  - wayland-utils
  - wayvnc
  - wdisplays
  - wget
  - whiptail
  - wireplumber
  - wl-clipboard
  - wofi
  - wtype
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - xdg-user-dirs
  - xdg-utils
  - xorg
  - xwayland
  - xz-utils
  - yazi
  - zlib1g
  - zlib1g-dev
  - zoom
  - zoxide
  - zsh
  - zstd
