#!/usr/bin/env bash
set -e

# This script is just meant to install any core required deps

# Requires root and does not expect sudo to be installed
[ "$UID" -eq 0 ] || { echo "This script must be run as root."; exit 1;}


apt install -y build-essential unzip scdoc cmake meson cava fonts-font-awesome fonts-jetbrains-mono fonts-noto-color-emoji fonts-roboto tmux
