[font]
size = 22.0
builtin_box_drawing = true

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 1
